name: Deploy Main Branch to GHCR

on:
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI
  release:
    types: [published] # Triggers on release publication

concurrency: # Ensures only one deployment job runs at a time for a given ref
  group: deploy-${{ github.ref }}
  cancel-in-progress: true # Cancels any in-progress runs for the same group when a new one starts

jobs:
  build_and_push_main: # Or your job name
    runs-on: ubuntu-latest

    permissions: # Recommended: Explicitly grant permissions needed by this workflow
      contents: read   # To checkout the repository code
      packages: write  # To push images to GitHub Container Registry (GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to fetch your repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Sets up Docker Buildx for advanced build features

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # Automatically gets the GitHub username or organization name
          password: ${{ secrets.GHCR_TOKEN }}     # Uses the PAT stored as a GitHub Secret

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64   # Defines the target platform for the image
          push: true               # Tells the action to push the image to the registry
          tags: |
            ghcr.io/pinionless/garmin-to-dawarich-sync:latest
            ghcr.io/pinionless/garmin-to-dawarich-sync:${{ github.event.release.tag_name }}

      - name: Logout from GitHub Container Registry
        if: always()
        run: docker logout ghcr.io # Ensures logout even if previous steps fail